name: Korean Docs Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "docs/site/**"
      - "packages/**"
      - "turbo.json"
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build documentation site
        run: cd docs/site && pnpm build
        env:
          TURBO_TELEMETRY_DISABLED: 1
