name: Korean Docs Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "docs/site/**"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: cd docs/site && pnpm install

      - name: Build documentation
        run: cd docs/site && pnpm build
